In [1]:
import numpy as np

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
B = A + I
B

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [19]:
u = np.array([(1, 2, 3)])
C = u * B
C

array([[ 2.,  4.,  9.],
       [ 4., 12., 18.],
       [ 7., 16., 30.]])

In [20]:
D = np.linalg.inv(C)
D

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-5.00000000e-01,  2.50000000e-01,  2.22044605e-17],
       [ 1.66666667e+00,  3.33333333e-01, -6.66666667e-01]])